multinode: false

modelArtifacts:
  uri: "hf://Qwen/Qwen3-0.6B"
  name: "Qwen/Qwen3-0.6B"
  size: 20Gi
  authSecretName: "llm-d-hf-token"

routing:
  proxy:
    enabled: false  # removes sidecar from deployment - no PD in inference scheduling
    targetPort: 8000  # controls server port to matchup with sidecar if deployed

accelerator:  # controls specialized hardware Type
  type: nvidia

decode:
  create: true
  replicas: 2
  monitoring:
    podmonitor:
      enabled: true
      portName: "sglang"  # decode service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
  - name: "sglang"
    image: docker.io/lmsysorg/sglang:v0.5.6.post2
    command: ["python3", "-m", "sglang.launch_server"]
    args:
      - "--model-path"
      - "Qwen/Qwen3-0.6B"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--enable-metrics"
      - "--log-level"
      - "debug"
    env:
      - name: CUDA_VISIBLE_DEVICES
        value: "0"
      - name: UCX_TLS
        value: "cuda_ipc,cuda_copy,tcp"
      - name: TRITON_CACHE_DIR
        value: /.cache
    ports:
      - containerPort: 8000
        name: sglang
        protocol: TCP
    resources:
      limits:
        nvidia.com/gpu: "1"
      requests:
        nvidia.com/gpu: "1"
    mountModelVolume: true
    volumeMounts:
    - name: metrics-volume
      mountPath: /.config
    - name: torch-compile-cache
      mountPath: /.cache
    startupProbe:
      httpGet:
        path: /v1/models
        port: sglang
      initialDelaySeconds: 15
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 60
    livenessProbe:
      httpGet:
        path: /health
        port: sglang
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /v1/models
        port: sglang
      periodSeconds: 5
      timeoutSeconds: 2
      failureThreshold: 3
  volumes:
  - name: metrics-volume
    emptyDir: {}
  - name: torch-compile-cache
    emptyDir: {}

# PD disabled in this example
prefill:
  create: false
